# Copyright (c) 2025 Embeint Holdings Pty Ltd
# SPDX-License-Identifier: FSL-1.1-ALv2

name: clang-format

on:
  pull_request:
    paths:
    - '.github/workflows/clang-format.yml'
    - '**/*.c'
    - '**/*.h'

permissions:
  contents: read

jobs:
  formatting-check:
    name: Formatting check on repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@6cd220de46c89139a0365edae93eee8eb30ca8fe # v4.16.0
      with:
        # Default version shipped with `ms-vscode.cpptools`
        clang-format-version: '21'
        exclude-regex: (lib/crypto/ascon)|(lib/crypto/XKCP)
